server:
  port: 8081
  mode: debug
  read_timeout: 10s
  write_timeout: 10s

mysql:
  dsn: root:126070mxZ@tcp(127.0.0.1:3306)/dianping?charset=utf8mb4&parseTime=True&loc=Local
  max_idle_conns: 10
  max_open_conns: 50

redis:
  addr: 127.0.0.1:6379
  password: "126070mxZ"
  db: 1

kafka:
  brokers:
    - localhost:9094
    - localhost:9095
    - localhost:9096
  topic: kafka-orders
  group_id: my-kafka-group
  enabled: true

upload:
  image_dir: 'D:\HeiMaDianPing\nginx-1.18.0\html\hmdp\imgs\'
  public_prefix: /imgs

auth:
  compatible_missing_token: false
